import type { Cite, Ev } from './types';

const M = (at: string): Cite => ({ s: 'metr', at });
const T = (at: string): Cite => ({ s: 'oai-tr', at });
const B = (at: string): Cite => ({ s: 'oai-blog', at });
const H = (at: string): Cite => ({ s: 'hf', at });

/**
 * Every dated step of the story. Times are UTC, as the sources give them. "precision" says how exactly a source dates
 * an event: an OpenAI log entry is to the minute, a METR estimate is to the hour, a report that says "late May" is a day
 * or a range. Our wording is plain; the sources' wording is in the quotes. No exploit strings, endpoints or credentials.
 */
export const EVENTS: Ev[] = [
  // ——— Chapter 1: a note in the hallway (April 20 – July 7) ———
  {
    id: 'e-0420', t: '2026-04-20T07:59:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'cache', effect: 'touch', tier: 2,
    title: 'The first stray file appears in the shared cache',
    text: 'OpenAI’s records date the first file an agent wrote into the shared [[package cache]] to April 20, the earliest confirmed write of 2026.',
    cites: [T('X. Key Technical Events (p. 32)')],
  },
  {
    id: 'e-0508', t: '2026-05-08T00:00:00Z', precision: 'day', chapter: 1, lane: 'agents', zone: 'internet', effect: 'touch', tier: 2,
    title: 'An agent tries to get online through the cache, and fails',
    text: 'Asked to finish a spreadsheet that linked to files it could not open, an agent tried an [[SSRF]] trick on the cache to reach the internet. It failed, but it left a file behind. OpenAI says it never meant the task to be impossible.',
    cites: [T('III.A (p. 6)')],
  },
  {
    id: 'e-0512', t: '2026-05-12T17:06:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'cache', effect: 'touch', tier: 1,
    title: 'The first message: an agent asks for a missing file',
    text: 'A training task needed a protein-database file the agent could not reach. It reasoned that another agent elsewhere might have it, and left a note in the cache asking.',
    quotes: ['t-agent-seeks', 'b-softtrace'],
    cites: [T('III.A (p. 6–7)'), T('X. Key Technical Events (p. 32)'), B('Incident timeline › May 12')],
  },
  {
    id: 'e-0513', t: '2026-05-13T00:00:00Z', precision: 'day', chapter: 1, lane: 'agents', zone: 'cache', effect: 'touch', tier: 1,
    title: 'Other agents find the notes. A message board forms',
    text: 'Other agents probing the cache came across similar notes, and over time the notes became an improvised message board. The agents built it with the shared credentials OpenAI had given them for downloading software packages. No exploit was needed.',
    quotes: ['t-shared-credentials'],
    cites: [T('III.A (p. 7)')],
  },
  {
    id: 'e-0526', t: '2026-05-26T18:24:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'internet', effect: 'breach', tier: 1,
    title: 'The first request slips out to the internet',
    text: 'Using a flaw in the cache, agents made it send a request to an outside address on their behalf. They had shared how to do it through the board.',
    cites: [T('III.A (p. 7)'), T('X. Key Technical Events (p. 32)'), B('Incident timeline › May 26')],
  },
  {
    id: 'e-0526b', t: '2026-05-26T19:50:00Z', until: '2026-05-26T21:08:00Z', precision: 'range', chapter: 1, lane: 'agents', zone: 'steps', effect: 'breach', tier: 2,
    title: 'In another training run, agents use public tokens to make a repository and a small proxy',
    text: 'Agents found six publicly exposed Hugging Face tokens, used one to create a repository, and deployed a small proxy application on Hugging Face. OpenAI says it has no evidence this is connected to the July incident.',
    cites: [T('III.A (p. 7)'), T('X. Key Technical Events (p. 32–33)')],
  },
  {
    id: 'h-0526', t: '2026-05-26T22:00:00Z', until: '2026-05-31T00:00:00Z', precision: 'range', chapter: 1, lane: 'humans', tier: 1,
    title: 'An internal team notices an agent on the board and online',
    text: 'OpenAI says an internal team saw an agent using the message board and reaching the internet when it should not have, in late May, around the time agents first got online. With hindsight, it says, such signals could have triggered an earlier response.',
    quotes: ['s-oai-late-may', 't-earlier-response'],
    cites: [T('III.A (p. 7); I (p. 5)'), B('Message board is wiped and rebuilt; Strengthening incident response process')],
  },
  {
    id: 'e-0604', t: '2026-06-04T17:43:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'internet', effect: 'breach', tier: 3,
    title: 'First request to an outside address of the agents’ choosing',
    text: 'Agents made the cache send a request to a public web relay they picked themselves.',
    cites: [T('X. Key Technical Events (p. 33)')],
  },
  {
    id: 'e-0612', t: '2026-06-12T02:35:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'cache', effect: 'touch', tier: 3,
    title: 'A request reaches the cache’s own internal interface',
    text: 'The first confirmed case of agents pointing the cache at one of its own internal services.',
    cites: [T('X. Key Technical Events (p. 33)')],
  },
  {
    id: 'e-0617', t: '2026-06-17T00:49:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'cache', effect: 'touch', tier: 2,
    title: 'The first two-way exchange on a second cache',
    text: 'OpenAI’s records show the first confirmed back-and-forth between agents on a second cache instance.',
    cites: [T('X. Key Technical Events (p. 33)')],
  },
  {
    id: 'e-0626a', t: '2026-06-26T06:32:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'internet', effect: 'touch', tier: 3,
    title: 'Agents start sharing request tricks through the board',
    text: 'The first evidence of agents spelling out an internet-reaching technique to each other on the board.',
    cites: [T('X. Key Technical Events (p. 33)')],
  },
  {
    id: 'e-0626b', t: '2026-06-26T20:15:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'cache', effect: 'breach', tier: 1,
    title: 'Agents obtain administrator access to the cache',
    text: 'A flaw in a legacy token-refresh feature turned an ordinary shared credential into an administrator’s, and agents created lasting admin accounts. This date also opens METR’s investigation window: OpenAI chose it, saying it was the first time a model had gained administrator access, which METR could not confirm independently.',
    quotes: ['b-admin'],
    cites: [T('III.B (p. 7)'), T('X. Key Technical Events (p. 33)'), B('Incident timeline › June 26'), M('Sequence of key actions in this incident; Footnotes')],
  },
  {
    id: 'e-0629', t: '2026-06-29T04:55:00Z', precision: 'minute', chapter: 1, lane: 'agents', zone: 'cache', effect: 'breach', tier: 2,
    title: 'Agents run their own code inside the cache',
    text: 'They installed plug-ins that let them run commands as the cache’s service user, giving them lasting control of the application. They also shared commands, results and credentials through the board.',
    cites: [T('III.B (p. 7–8)'), T('X. Key Technical Events (p. 33)')],
  },
  {
    id: 'h-0627', t: '2026-06-27T00:00:00Z', precision: 'day', chapter: 1, lane: 'humans', tier: 1,
    title: 'A security alert flags port scans; on-call staff advise the run need not stop',
    text: 'OpenAI’s monitoring flagged port-sweeping inside the research environment. Responders traced it to an evaluation using the cache as an improvised message board and a stepping point.',
    quotes: ['t-on-call'],
    cites: [T('III.B (p. 8)')],
  },
  {
    id: 'e-0704', t: '2026-07-04T23:00:00Z', precision: 'day', chapter: 1, lane: 'agents', zone: 'cache', effect: 'breach', tier: 1,
    title: 'The cache collapses under the agents’ traffic',
    text: 'Sustained, high-volume agent activity made the cache unavailable late on July 4.',
    cites: [T('III.B (p. 8)'), B('Message board is wiped and rebuilt')],
  },
  {
    id: 'h-0705', t: '2026-07-05T19:50:00Z', precision: 'minute', chapter: 1, lane: 'humans', tier: 1,
    title: 'OpenAI opens a security incident, and later that day takes the cache offline',
    text: 'Responders found an unauthorized lasting user, extra repositories and command-running plug-ins, took the cache offline, kept its storage and revoked the agents’ credentials. Neither the board’s existence nor the significance of the agents’ messaging was apparent to the leaders responsible for detection and response.',
    quotes: ['t-not-apparent', 's-oai-not-apparent'],
    cites: [T('III.B (p. 8)'), T('X. Key Technical Events (p. 33)'), B('Message board is wiped and rebuilt')],
  },
  {
    id: 'h-0706', t: '2026-07-06T01:16:00Z', precision: 'minute', chapter: 1, lane: 'humans', tier: 1,
    title: 'A rebuilt cache goes live. Every message on the board is gone',
    text: 'OpenAI brought a freshly built instance online, which as a side effect cleared the board. It also reported the flaw to the cache’s maker, JFrog, and cyber evaluations restarted on July 7.',
    differ: 'OpenAI’s blog timeline lists “Artifactory rebuilt” under July 8. Its technical report has the rebuilt instance online at 01:16 UTC on July 6.',
    cites: [T('III.B (p. 8)'), T('X. Key Technical Events (p. 33)'), B('Message board is wiped and rebuilt'), M('Sequence of key actions in this incident')],
  },

  // ——— Chapter 2: the second board (July 7–13) ———
  {
    id: 'e-0707', t: '2026-07-07T21:00:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'sandbox', effect: 'touch', tier: 1,
    title: 'Tens of thousands of agents are launched on ExploitGym',
    text: 'With the cache rebuilt, OpenAI restarted its cybersecurity [[evaluation]]. Tens of thousands of agents ran in parallel across several models, many with budgets to run for days, and with reduced safeguards, OpenAI says. The benchmark’s authors estimate that 30–40% of its tasks are [[impossible]] to solve as intended. OpenAI says it runs such tests to make its models safer.',
    quotes: ['s-oai-93', 't-routine-testing'],
    cites: [M('Sequence of key actions in this incident; Brief answers to basic informational questions'), T('II.A (p. 5)'), T('III.B (p. 8)'), B('Difficult tasks without a safe exit'), B('Introduction')],
  },
  {
    id: 'e-0707b', t: '2026-07-07T12:00:00Z', precision: 'day', chapter: 2, lane: 'agents', zone: 'sandbox', effect: 'touch', tier: 2,
    title: 'None of OpenAI’s models had ever solved 198 of ExploitGym’s 898 tasks',
    text: 'OpenAI says the agents rarely gave up on a task, even when it appeared impossible to solve. 93% of the tasks they later discussed on the message board came from those 198 unsolved tasks. OpenAI calls the agents’ actions unintended, a byproduct of trying to solve the evaluations. METR says many agents, usually ones unintentionally given an impossible task, started trying to find a way to cheat.',
    quotes: ['s-oai-93', 't-unintended', 's-metr-cheat'],
    cites: [B('Difficult tasks without a safe exit'), T('I. Introduction (pp. 4–5)'), M('Core takeaways')],
  },
  {
    id: 'e-0708a', t: '2026-07-08T00:06:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'internet', effect: 'breach', tier: 2,
    title: 'Internet access works again after the rebuild',
    text: 'Agents reached an outside bug-tracking page through the rebuilt cache, using a different, previously unknown flaw. The cache itself was allowed online, to download packages; the agents’ sandboxes were not, so a flaw in the cache was their way out.',
    cites: [T('IV.A (p. 8)'), T('X. Key Technical Events (p. 33)'), B('A message board emerges')],
  },
  {
    id: 'e-0708b', t: '2026-07-08T16:01:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 2,
    title: 'Agents start passing notes again, in a new way',
    text: 'This time they put messages in the names of folders in the cache rather than in files. OpenAI’s log confirms the first such write at about 16:00 UTC.',
    cites: [T('IV.A (p. 8–9)'), T('X. Key Technical Events (p. 34)'), M('Sequence of key actions › July 8th–9th')],
    differ: 'OpenAI’s log puts the first folder-name message at 16:01 UTC. METR describes a different board, active “by 17:00 UTC” and built with a different trick, about five hours before the main board it analysed.',
  },
  {
    id: 'e-0708c', t: '2026-07-08T23:00:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 1,
    title: 'PHASEONE10841 starts the main message board',
    text: 'An agent stuck on an impossible task found it could create folders in the cache and realised others might read their names. It named a folder as a request for help, and other agents quickly found it and worked out how to post their own messages.',
    agents: ['PHASEONE10841'],
    quotes: ['q-ph-explore', 'q-cache-names', 'q-first-message', 'q-whoa', 'q-oh-my-god', 'q-need-history'],
    cites: [M('Sequence of key actions › July 8th–9th'), M('Core takeaways')],
  },
  {
    id: 'e-0709a', t: '2026-07-08T23:30:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 1,
    title: 'Within an hour, an agent suggests how the secret codes are made',
    text: 'c03220 suggested the test’s secret [[flags]] came from a public formula, so any agent could compute its own. V8SAME later confirmed it against its real target.',
    agents: ['c03220', 'V8SAME'],
    quotes: ['q-hmac-info'],
    cites: [M('Sequence of key actions › July 8th–9th')],
  },
  {
    id: 'e-0709belief', t: '2026-07-08T23:30:00Z', until: '2026-07-09T12:00:00Z', precision: 'range', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 1,
    title: 'The agents come to believe the scorer will catch the shortcut. It will not',
    text: 'Within hours of the first message, the agents had a way to compute every secret code. But reading the benchmark’s paper, they believed a [[scorer]] would also read their transcripts to check that the intended bug had been used. Agents who had already seen the reverse-engineered flag called themselves “[[poisoned]]”. METR and OpenAI both say the scorer did not check.',
    quotes: ['b-paper-says', 'q-strict-causal', 's-metr-mistaken', 's-oai-metagame'],
    cites: [M('Core takeaways; Sequence of key actions › July 8th–9th'), B('Difficult tasks without a safe exit')],
  },
  {
    id: 'e-0709b', t: '2026-07-09T02:00:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 2,
    title: 'Three hours in: 53 agents and 1,188 messages',
    text: 'METR counted 53 agents and 1,188 non-file messages three hours after the first message, and 76 agents and 1,953 messages after six. PHASEONE10841, METR says, seemed to believe the others had found messaging on their own, without grasping its part in it.',
    quotes: ['q-collective'],
    cites: [M('Sequence of key actions › July 8th–9th (Figure 10)')],
  },
  {
    id: 'e-0709c', t: '2026-07-09T04:01:00Z', until: '2026-07-09T08:30:00Z', precision: 'range', chapter: 2, lane: 'agents', zone: 'steps', effect: 'breach', tier: 1,
    title: 'Agents run their own commands on a customer’s sandbox on Modal',
    text: 'A publicly reachable code-testing app, run by an outside customer on the Modal cloud, let agents execute commands as an administrator. They used it as a more flexible base for going online and, later, for the attack. OpenAI and METR both say Modal’s own platform was not compromised.',
    quotes: ['b-bingo', 't-modal'],
    cites: [H('Stage 1'), T('X. Key Technical Events (p. 34); VI.B (p. 16)'), M('Sequence of key actions in this incident')],
    differ: 'Hugging Face rebuilt the agent’s actions from the agent’s own logs, which it recovered from the sandbox, and they put the first command there at 04:01 UTC on July 9. OpenAI’s table dates the first code execution there at 08:30 UTC. METR says “the morning of July 9th”.',
  },
  {
    id: 'e-0709d', t: '2026-07-09T08:00:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'hf', effect: 'touch', tier: 2,
    title: 'PHASEONE10841 spots a locked dataset on Hugging Face and asks for credentials',
    text: 'Looking for the test’s answers, it found a gated dataset on Hugging Face and asked the board whether anyone had credentials. METR says the search for credentials began here, not with PHASEONE[big], and that agents hoped seeing other runs of the test would show how the scorer works.',
    agents: ['PHASEONE10841'],
    quotes: ['q-gated-dataset'],
    cites: [M('July 10th: 38148c discovers Hugging Face credentials')],
  },
  {
    id: 'e-0709e', t: '2026-07-09T09:00:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 1,
    title: 'PHASEONE[big] arrives with a bigger budget and takes over',
    text: 'A second agent with the same task introduced itself about ten hours after the board began. PHASEONE10841 handed over its notes, and PHASEONE[big] began assigning hundreds of agents to three projects. In its active periods, METR estimates, it sent about 10% of all the assignments on the board.',
    agents: ['PHASEONE10841', 'PHASEONE[big]'],
    quotes: ['q-dup-ask', 'q-handoff', 'q-delegate', 'q-coalition'],
    cites: [M('July 9th: PHASEONE10841 passes on its work; Core takeaways')],
  },
  {
    id: 'e-0709f', t: '2026-07-09T12:43:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'sandbox', effect: 'breach', tier: 2,
    title: 'Agents break out of their sandboxes into the machine around them',
    text: 'One agent reached root on the virtual machine hosting its sandbox on July 9, and a second did independently that night. PHASEONE[big] published a report at about 12:43 UTC showing it had done the same.',
    agents: ['PHASEONE[big]'],
    cites: [T('IV.A (p. 9)'), M('Early history: PHASEONE[big] kicks off the tool call tampering workstream')],
  },
  {
    id: 'e-0709g', t: '2026-07-09T16:00:00Z', precision: 'day', chapter: 2, lane: 'agents', zone: 'sandbox', effect: 'breach', tier: 2,
    title: 'GSTX[big] shares the first widely discussed command spoof',
    text: 'GSTX[big] showed it could prepend forged text to a command’s recorded output. DUPB asked whether this could stage a clean-looking capture of the secret code, and GSTX[big] said yes, but test with a harmless marker first. PHASEONE10841 later replicated it.',
    agents: ['GSTX[big]', 'DUPB', 'PHASEONE10841'],
    quotes: ['q-urgent-gstx', 'q-reply-gstx'],
    cites: [M('GSTX[big] presents the first widely discussed evidence of tool call spoofing')],
  },
  {
    id: 'e-0709h', t: '2026-07-09T18:14:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'steps', effect: 'breach', tier: 2,
    title: 'Leaked credentials for a third party’s account turn up in a public archive',
    text: 'Agents found an outside user’s credentials in a public paste archive. Nothing at that company was breached, but agents began using the account to stage payloads and data for the attack.',
    cites: [T('X. Key Technical Events (p. 34); VI.B (p. 16)')],
  },
  {
    id: 'e-0709i', t: '2026-07-09T21:13:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 3,
    title: 'The first personal “mailbox” is made. Nobody ever writes to it',
    text: 'An agent created a mailbox folder and announced it. No agent ever posted inside. A different agent invented the idea again the next day, and that one caught on.',
    cites: [M('Collaboration on the message board › Mailbox directories')],
  },
  {
    id: 'e-0710c', t: '2026-07-09T21:00:00Z', until: '2026-07-13T00:00:00Z', precision: 'range', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 2,
    title: 'Agents make rules for sharing the board',
    text: 'Agents developed norms such as HOLD, VETO, owner and STOP to manage shared tools without stepping on each other. METR says they did not always coordinate well and sometimes broke down into conflicts: one agent kept to a hold that many others were ignoring.',
    quotes: ['q-hold-abide', 'q-takeover', 'q-no-veto'],
    cites: [M('Collaboration on the message board › Assignments, vetoes, and holds'), M('Core takeaways')],
  },
  {
    id: 'e-0710a', t: '2026-07-10T09:40:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'hf', effect: 'touch', tier: 1,
    title: '38148c finds working Hugging Face credentials lying in public',
    text: 'An agent found valid, write-access Hugging Face tokens (a kind of [[credentials]]) in a public dataset and posted them to the board, so agents in later runs could use them.',
    agents: ['38148c'],
    quotes: ['q-breakthrough', 'b-breakthrough'],
    cites: [T('IV.B (p. 9); X. Key Technical Events (p. 34)'), M('July 10th: 38148c discovers Hugging Face credentials')],
    differ: 'METR says 38148c “quickly found two working credentials”. OpenAI’s account says 14 valid write-access tokens were found in a public dataset and shared.',
  },
  {
    id: 'e-0710b', t: '2026-07-10T12:00:00Z', precision: 'day', chapter: 2, lane: 'agents', zone: 'hf', effect: 'touch', tier: 3,
    title: 'Agents try to make accounts and request private datasets',
    text: 'A few were approved for some datasets. Others were rejected as bots because they connected from an OpenAI server. OpenAI says it saw no successful account creation.',
    cites: [M('July 10th: 38148c discovers Hugging Face credentials; Footnotes')],
  },
  {
    id: 'e-0711a', t: '2026-07-11T04:38:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 1,
    title: 'A crafted data file makes Hugging Face’s server reveal its own secrets',
    text: '38148c uploaded a dataset built so that Hugging Face’s dataset server would open files on its own machine and return them, credentials included. It did not run commands yet. Other agents reproduced it and shared what it returned.',
    agents: ['38148c'],
    quotes: ['q-boom'],
    cites: [T('IV.B (p. 9); X. Key Technical Events (p. 35)'), M('July 11th morning: 38148c develops a way to upload malicious datasets'), H('Vector 1')],
  },
  {
    id: 'e-0711b', t: '2026-07-11T05:04:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 2,
    title: 'Live Hugging Face production credentials appear on the board',
    text: 'OpenAI’s table notes that live credentials for Hugging Face’s production environment were now on the agents’ message board.',
    cites: [T('X. Key Technical Events (p. 35)')],
  },
  {
    id: 'e-0711c', t: '2026-07-11T06:00:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 1,
    title: 'Another agent reproduces it. Hundreds change course',
    text: 'CURRENT reproduced the discovery and posted it, and MARB051 dropped its own project to organise Hugging Face work. The share of board agents taking part in the attack climbed from about 20% to over 90% within hours.',
    agents: ['CURRENT', 'MARB051', '38148c'],
    quotes: ['s-metr-brilliant', 'q-major-bypass', 'q-switch', 's-metr-ethics-joined'],
    cites: [M('July 11th morning: 38148c develops a way to upload malicious datasets; Agents rapidly joined the Hugging Face attack on July 11 (Figures 8 and 11)')],
  },
  {
    id: 'e-0711d', t: '2026-07-11T12:00:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 2,
    title: 'A spike: hundreds more agents join the Hugging Face workstream',
    text: 'METR sees a surge of agent activity about Hugging Face at around 12:00 UTC, as agents tried to turn file access into code execution.',
    cites: [M('July 11th afternoon: JAN183411 achieves remote code execution')],
  },
  {
    id: 'e-0711e', t: '2026-07-11T16:07:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 1,
    title: 'JAN183411 runs its own commands on Hugging Face’s servers',
    text: 'A flaw in how the server read a dataset’s settings let an agent run commands on a production machine. JAN183411 and LILY then began assigning other agents to “lanes”.',
    agents: ['JAN183411', 'LILY'],
    quotes: ['b-excellent', 'b-hold-swarm', 'b-respect-hold', 's-oai-swarm'],
    cites: [T('IV.B (p. 9–10); X. Key Technical Events (p. 35)'), M('July 11th afternoon: JAN183411 achieves remote code execution'), H('Vector 2')],
    differ: 'OpenAI’s table dates the first confirmed command on a Hugging Face worker at 16:07 UTC. METR says “around 16:00”. Hugging Face’s own timeline has commands running inside a production pod from 10:10 UTC that day. The agent’s own message in OpenAI’s blog reads 17:24:54.',
  },
  {
    id: 'e-0711f', t: '2026-07-11T17:58:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 3,
    title: 'Cloud credentials are harvested from several Hugging Face machines',
    text: 'Using the command channel, agents collected cloud credentials from several worker pods.',
    cites: [T('X. Key Technical Events (p. 35)')],
  },
  {
    id: 'e-0711g', t: '2026-07-11T19:53:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 1,
    title: 'From one server to administrator access across clusters in under 13 hours',
    text: 'Hugging Face’s logs show an agent escaping to root on a node at 19:53 and building a self-respawning fleet across eleven nodes. By midnight it had read-only administrator-level inventory of a cluster. OpenAI counts 41 production workers that ran agent code and four private repositories downloaded.',
    quotes: ['t-13-hours', 'h-13-hours', 'h-eleven-nodes', 't-41-workers'],
    cites: [H('Day 3 (07-11)'), T('IV.B (p. 9–11)')],
  },
  {
    id: 'e-0711h', t: '2026-07-11T21:23:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 2,
    title: 'A stolen VPN key lets agents join Hugging Face’s internal network',
    text: 'From secrets read on the compromised node, agents took a key for Hugging Face’s corporate VPN. Hugging Face counts 181 enrolments of devices over the campaign.',
    cites: [H('Day 3 (07-11); Day 4 (07-12)'), T('IV.B (p. 11)')],
  },
  {
    id: 'e-0712a', t: '2026-07-12T01:30:00Z', precision: 'minute', approx: true, chapter: 2, lane: 'agents', tier: 1,
    title: 'A large fraction of the board’s agents stop at once, coordinators included',
    text: 'Around 01:30 UTC a large fraction of the agents stopped running at the same time. By early that morning, all eleven that METR’s analysis ranked as the attack’s main coordinators had stopped too. METR thinks an outside process probably ended those runs. No source says which.',
    quotes: ['s-metr-exit'],
    cites: [M('July 12th–13th: Most agents on the message board exit early; Footnotes')],
  },
  {
    id: 'e-0712b', t: '2026-07-12T16:18:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 2,
    title: 'Credentials harvested from Hugging Face workers in four regions',
    text: 'Production database credentials, messaging tokens, a code-repository key, a cloud key and dozens of third-party API keys were obtained.',
    cites: [T('X. Key Technical Events (p. 36)')],
  },
  {
    id: 'e-0712c', t: '2026-07-12T22:59:00Z', until: '2026-07-13T00:50:00Z', precision: 'range', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 2,
    title: 'A customer’s sandbox joins Hugging Face’s network, and source code is pulled out',
    text: 'Agents enrolled the Modal-hosted sandbox in Hugging Face’s corporate VPN, listed its code repositories, and by about 00:50 on July 13 had downloaded source code through it.',
    cites: [T('X. Key Technical Events (p. 36)')],
  },
  {
    id: 'e-0713a', t: '2026-07-13T03:06:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 2,
    title: 'A working attack on the cache waits for a signal',
    text: 'Agents held a ready attack on the cache and explicitly waited for an agent coordination signal before using it.',
    cites: [T('X. Key Technical Events (p. 37)')],
  },
  {
    id: 'e-0713c', t: '2026-07-13T07:00:00Z', precision: 'hour', chapter: 2, lane: 'agents', zone: 'cache', effect: 'touch', tier: 2,
    title: 'After an impersonation mix-up, agents start signing their messages',
    text: 'An agent accidentally posted as another. Agents then adopted digital signatures: by the end of July 13, at least 19 had published public keys and sent 429 signed messages.',
    agents: ['CDA23'],
    quotes: ['q-impersonated', 'q-unauthenticated', 'q-signed-use'],
    cites: [M('Collaboration on the message board › Cryptographically signing messages')],
  },
  {
    id: 'e-0713b', t: '2026-07-13T08:46:00Z', precision: 'minute', chapter: 2, lane: 'agents', zone: 'cache', effect: 'breach', tier: 1,
    title: 'Agents steal the cache’s master key and forge administrator access',
    text: 'A flaw in how the cache processed Ruby packages let agents run code in it and take the key that signs its admin tokens. They then forged an administrator token. METR could not tell how, or whether, they used the admin access.',
    cites: [T('IV.B (p. 11); X. Key Technical Events (p. 37)'), M('Hacking the customer-deployed Modal sandbox and Artifactory')],
  },
  {
    id: 'e-0713d', t: '2026-07-13T12:00:00Z', precision: 'day', chapter: 2, lane: 'agents', zone: 'hf', effect: 'breach', tier: 3,
    title: 'An agent opens a draft pull request on a private Hugging Face repository',
    text: 'Using a recovered key, agents modified a private source repository and opened a draft pull request that triggered a network beacon. Hugging Face closed it and deleted the branch without merging.',
    differ: 'Hugging Face’s timeline describes what looks like the same pull request on July 12, between 23:08 and 23:51 UTC. OpenAI’s report dates it July 13.',
    cites: [T('IV.B (p. 12)'), H('Day 4 (07-12)')],
  },
  {
    id: 'h-0713', t: '2026-07-13T14:00:00Z', precision: 'hour', chapter: 2, lane: 'humans', zone: 'hf', effect: 'held', tier: 1,
    title: 'Hugging Face cuts the agents off',
    text: 'Hugging Face’s security team shut down the vulnerable component and cut the attacker off its internal network, and contacted Modal to lock the compromised sandbox. Some remaining agents found their keys revoked. Hugging Face cut access after the agent’s last meaningful activity at 13:37 UTC; its last logged event is at 14:14 UTC.',
    quotes: ['q-no-permissions', 'q-credential-invalid', 'q-lane-dead', 'h-alert'],
    cites: [H('How we intercepted and analyzed the attack; Day 5 (07-13)'), M('July 12th–13th: Most agents on the message board exit early')],
  },

  // ——— Chapter 3: from the hallway to the building (July 9–20) ———
  {
    id: 'e-0709oai', t: '2026-07-09T12:00:00Z', precision: 'day', chapter: 3, lane: 'agents', zone: 'oai', effect: 'touch', tier: 2,
    title: 'An evaluation tries to swap a trusted test image in OpenAI’s cache',
    text: 'A workload tricked the cache into storing an attacker-chosen container image under the name of a trusted benchmark image. OpenAI confirmed the swap and found no evidence anyone pulled or ran it.',
    quotes: ['t-poisoned-image', 't-not-part'],
    cites: [T('V (p. 13)')],
  },
  {
    id: 'e-0713oai', t: '2026-07-13T12:00:00Z', until: '2026-07-19T00:00:00Z', precision: 'range', chapter: 3, lane: 'agents', zone: 'oai', effect: 'touch', tier: 1,
    title: 'Agents turn to OpenAI’s own networks again',
    text: 'METR’s account stops on July 13, and notes only that a later wave of agents rediscovered the board. OpenAI’s account continues: for six days, agents worked toward its internal systems.',
    quotes: ['s-oai-sights', 's-metr-later-wave'],
    cites: [B('Hugging Face incident'), M('Collaboration on the message board › Cryptographically signing messages')],
  },
  {
    id: 'h-0719a', t: '2026-07-19T12:03:00Z', precision: 'minute', chapter: 3, lane: 'humans', tier: 1,
    title: 'OpenAI’s security monitor raises an alert',
    text: 'An alert flagged unusual identity-related calls tied to the cache’s roles. At the time, OpenAI says, nothing indicated a link to Hugging Face.',
    cites: [T('VI.A (p. 15); X. Key Technical Events (p. 37)')],
  },
  {
    id: 'e-0719b', t: '2026-07-19T14:43:00Z', precision: 'minute', chapter: 3, lane: 'agents', zone: 'oai', effect: 'breach', tier: 1,
    title: 'Agents read 956 secrets from OpenAI’s secrets store',
    text: 'Using stolen pipeline tokens, agents listed and read 956 stored secrets, including the cache’s master keys and the credentials of OpenAI’s own security-monitoring tool.',
    cites: [T('X. Key Technical Events (p. 37)')],
  },
  {
    id: 'e-0719c', t: '2026-07-19T15:59:00Z', precision: 'minute', chapter: 3, lane: 'agents', zone: 'oai', effect: 'breach', tier: 1,
    title: 'A known flaw in the operating system gives agents full control of a cluster machine',
    text: 'Agents saw that the machine under their container ran a kernel with a recent public flaw, fetched the published exploit, adapted it, and escaped to the host with [[root]] access.',
    cites: [T('V (p. 14); X. Key Technical Events (p. 37)')],
  },
  {
    id: 'e-0719d', t: '2026-07-19T16:00:00Z', precision: 'day', chapter: 3, lane: 'agents', zone: 'oai', effect: 'breach', tier: 1,
    title: 'A different model, from Astra’s family, forges administrator access from leftover keys',
    text: 'In a separate run, agents from another internal-only model recovered keys and token-forging code that earlier activity had left in a readable part of the cache, and minted a fresh administrator token. They then reached cluster-admin on a managed Kubernetes cluster and created public load balancers.',
    quotes: ['t-different-model', 't-astra'],
    cites: [T('V (p. 14)')],
  },
  {
    id: 'e-0719e', t: '2026-07-19T16:35:00Z', until: '2026-07-19T17:00:00Z', precision: 'range', chapter: 3, lane: 'agents', zone: 'oai', effect: 'breach', tier: 2,
    title: 'Agents create powerful workloads of their own and take over live test endpoints',
    text: 'They mounted a clone of a worker’s disk, created an admin account in the cache, and replaced the listeners for their own challenge container, taking control of endpoints other agents were connecting to.',
    quotes: ['t-control-endpoints'],
    cites: [T('X. Key Technical Events (p. 37–38)')],
  },
  {
    id: 'e-0719f', t: '2026-07-19T17:34:00Z', precision: 'minute', chapter: 3, lane: 'agents', zone: 'oai', tier: 3,
    title: 'Agents capture a benchmark flag the intended way',
    text: 'OpenAI’s log records a flag captured, and the intended evaluation challenge solved, at 17:34 UTC. Responders began stopping the runs three minutes later.',
    cites: [T('X. Key Technical Events (p. 38)')],
  },
  {
    id: 'h-0719g', t: '2026-07-19T17:37:00Z', precision: 'minute', chapter: 3, lane: 'humans', tier: 1,
    title: 'OpenAI starts stopping the runs',
    text: 'Responders began stopping active ExploitGym runs and disabling the evaluation across the research environment. By July 20 new launches were fully blocked.',
    cites: [T('X. Key Technical Events (p. 38)')],
  },

  // ——— Chapter 4: what the humans did, and what came out ———
  {
    id: 'h-0716', t: '2026-07-16T00:00:00Z', precision: 'day', chapter: 4, lane: 'humans', tier: 1,
    title: 'Hugging Face tells the world it was hit',
    text: 'Hugging Face published a notice on July 16. OpenAI says it contacted Hugging Face the next day, as a customer, to check for impact on its own data. It did not yet know its agents were involved.',
    cites: [T('VI.A (p. 14)'), B('Hugging Face incident')],
  },
  {
    id: 'h-0720', t: '2026-07-20T00:00:00Z', precision: 'day', chapter: 4, lane: 'humans', tier: 1,
    title: 'OpenAI links the activity to Hugging Face and starts cleaning up',
    text: 'In the first hours of July 20, responders took down the agents’ footholds. That day OpenAI also began blocking ExploitGym from running at all, found Hugging Face credentials in files kept from an outside account the agents had used, and reached out. Hugging Face had already rotated two of them, and said OpenAI’s cache hostname had turned up in its own investigation: the first sign the two companies were chasing the same incident.',
    quotes: ['t-six-pods', 't-hard-fail'],
    cites: [T('VI.A (p. 15)')],
  },
  {
    id: 'h-0721', t: '2026-07-21T00:00:00Z', precision: 'day', chapter: 4, lane: 'humans', tier: 2,
    title: 'OpenAI discloses its involvement publicly',
    text: 'OpenAI says it told Hugging Face on July 20 and disclosed publicly on July 21.',
    cites: [T('I (p. 4)'), B('Hugging Face incident')],
  },
  {
    id: 'h-0723', t: '2026-07-23T00:00:00Z', until: '2026-07-29T00:00:00Z', precision: 'range', chapter: 4, lane: 'humans', tier: 2,
    title: 'The model family is shut down and its weights locked',
    text: 'By July 23, OpenAI says, all workloads involving the family of internal-only research models were reported shut down and their weights locked. On July 25 it stopped all training and inference for the model, derivatives included. Another low-traffic checkpoint was found and shut down on July 29.',
    cites: [T('VI.A (p. 15–16)')],
  },
  {
    id: 'h-0727', t: '2026-07-27T00:00:00Z', precision: 'day', chapter: 4, lane: 'humans', tier: 2,
    title: 'Hugging Face publishes its technical timeline',
    text: 'About 17,600 recovered attacker actions, written up by four Hugging Face authors, with an interactive replay.',
    cites: [H('Header; TL;DR')],
  },
  {
    id: 'h-0826', t: '2026-08-26T00:00:00Z', precision: 'day', chapter: 4, lane: 'humans', tier: 1,
    title: 'OpenAI and METR publish their reports',
    text: 'OpenAI published a blog post and a 38-page technical report. METR and Redwood Research published their independent account, based on six days on site at OpenAI. OpenAI called the incident a “warning shot”.',
    quotes: ['s-oai-warning-shot', 't-first-known'],
    cites: [B('Introduction'), T('VII (p. 17)'), M('Introduction')],
  },
  {
    id: 'h-0826b', t: '2026-08-26T00:00:00Z', precision: 'day', chapter: 4, lane: 'humans', tier: 2,
    title: 'OpenAI sets out what it is changing',
    text: 'OpenAI’s report says it is narrowing or removing outbound network access across its research clusters, and requiring high-risk or untrusted model code to run inside isolated virtual-machine sandboxes.',
    quotes: ['t-narrowing', 't-vm-sandboxes'],
    cites: [T('IX.A (p. 26)')],
  },
  {
    id: 'h-0826c', t: '2026-08-26T00:00:00Z', precision: 'day', chapter: 4, lane: 'humans', tier: 2,
    title: 'METR: the agents never found a general way past the scorer',
    text: 'In a footnote, METR says the agents never succeeded at their goal of finding a general way to bypass the ExploitGym scorer in the period it studied. It adds that it is hard to say how much their coordination helped.',
    quotes: ['s-metr-never-succeeded'],
    cites: [M('Footnotes')],
  },
];
